🧰: do not clear halo/property panel focus when interacting with tools
LivelyKernel/lively.next pull request #1200
Opened 2024-01-16 17:01 UTC by linusha

2024-01-18 07:50 UTC, merryman requested changes

2024-01-18 07:50 UTC, merryman commented on lively.ide/world.js
> +      this.morphsInWorld.includes(target) || // keep halo and properties panel focus around when interacting with tools
Maybe I am super confused but isnt the expression doing exactly the opposite of what the comment says?
When `target` is a tool, the expression returns false unlike true as the comment suggests.

2024-01-19 02:03 UTC, merryman commented on lively.ide/world.js
> +      this.morphsInWorld.includes(target) || // keep halo and properties panel focus around when interacting with tools
![many-halos](https://github.com/LivelyKernel/lively.next/assets/1296388/101fde15-7ea4-466a-a8d5-1bf044f07e81)

2024-01-19 16:50 UTC, linusha commented
@merryman yeah, the previous state of this PR was a bit of a mess, don't know how I got there. Now it should work as expected and make a lot more sense.

I am not super happy with the `setTimeout` I smuggled in here, but I couldn't think of an alternative solution with adequate size, given that this is only necessary for a very small scoped problem.

2024-01-20 03:34 UTC, merryman approved these changes
Looks good now!

2024-01-20 17:59 UTC, merged