Labels do not accept drops as default anymore
LivelyKernel/lively.next pull request #153
Opened 2021-01-06 09:43 UTC by linusha

This closes #108

2021-01-08 13:48 UTC, merryman requested changes

2021-01-08 13:48 UTC, merryman commented on lively.morphic/text/label.js
> +    this.acceptsDrops = false;
Actually the canonical way to achieve this is to set the defaultValue to `false` in the property definition of acceptsDrops.

2021-01-08 17:45 UTC, linusha commented
Okay, makes sense. Does it use the correct way now? :)

2021-01-14 11:54 UTC, merryman approved these changes

2021-01-14 11:54 UTC, merged