String widget respects custom border color
LivelyKernel/lively.next pull request #273
Opened 2021-05-19 16:24 UTC by SilvanVerhoeven

2021-05-19 16:35 UTC, frcroth commented on lively.ide/value-widgets.js
> +      debugger;
Remove

2021-05-24 13:44 UTC, merryman commented
Is this one ready?

2021-05-25 08:19 UTC, SilvanVerhoeven commented
Can now be merged @merryman 
Thanks for paying attention, @linusha :)

2021-05-25 11:41 UTC, merryman requested changes

2021-05-30 10:43 UTC, merryman commented on lively.ide/value-widgets.js
> +      _borderColor: {
@SilvanVerhoeven Once that change is in, this is ready to go.

2021-06-10 08:12 UTC, merged