morphic: add onHaloMouseDown event
LivelyKernel/lively.next pull request #381
Opened 2022-06-14 10:41 UTC by T4rikA

Event that gets fired if mouse click on morph with halo activated

2022-06-14 13:19 UTC, linusha requested changes

2022-06-15 14:34 UTC, T4rikA commented on lively.halos/morph.js
> +    this.target.onHaloMouseDown(evt);
True! I also added a return before the last condition, if this isn't the case we call `onHaloMouseDown`

2022-06-15 14:41 UTC, linusha approved these changes

2022-06-15 14:41 UTC, linusha commented
@T4rikA we would prefer a rebase over a merge commit, thanks!

2022-06-15 14:49 UTC, merged