🧰👤: decouple flap component from sidebars
LivelyKernel/lively.next pull request #606
Opened 2023-01-06 11:41 UTC by linusha

Allows to easily plug in other stuff than the sidebar into the flap components.

2023-01-09 14:22 UTC, merryman requested changes

2023-01-09 14:22 UTC, merryman commented on lively.ide/studio/sidebar-flap.js
> +  const { view } = this;
I gotta say, I would prefer this to be passed as an argument. I know this is technically possible but it just is super confusing to me to assume that when we are executing we are bound against a flap model.

2023-01-09 14:22 UTC, merryman commented on lively.ide/studio/flap.cp.js
> +    this.openingRoutine.bind(this)();
Can we just use these as plain callbacks without binding them dynamically agains the view model? We can just pass the view model as an argument to the callbacks. That way the callbacks being defined outside of the view model class could contain a parameter name like `flapViewModel` which makes things more clear than implicitly assuming this refers to the flap view model.

2023-01-10 12:44 UTC, linusha commented
Superseded by #613.

2023-01-10 12:44 UTC, closed without merging