Add check for node 19
LivelyKernel/lively.next pull request #688
Opened 2023-02-06 20:59 UTC by kholbekj

Currently, node 19 doesn't install.

2023-02-06 21:35 UTC, linusha commented
@merryman I can reproduce this. The error occurs when the bundling of the loading-screen and dashboard are attempted.

<pre>/home/linus/test/lively.next/lively.next-node_modules/@rollup__SLASH__plugin-json/4.1.0/dist/index.js:31
        var position = parseInt(/[\d]/.exec(err.message)[0], 10);
                                                        ^

TypeError: Cannot read properties of null (reading &apos;0&apos;)
    at Object.transform (/home/linus/test/lively.next/lively.next-node_modules/@rollup__SLASH__plugin-json/4.1.0/dist/index.js:31:57)
    at /home/linus/test/lively.next/lively.next-node_modules/rollup/2.68.0/dist/shared/rollup.js:22795:37
<font color="#555753">    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)</font> {
  code: <font color="#4E9A06">&apos;PLUGIN_ERROR&apos;</font>,
  plugin: <font color="#4E9A06">&apos;commonjs--resolver&apos;</font>,
  hook: <font color="#4E9A06">&apos;resolveId&apos;</font>,
  id: <font color="#4E9A06">&apos;https://jspm.dev/npm:ajv@6.12.6/lib/refs/json-schema-draft-07.json&apos;</font>,
  watchFiles: [
    <font color="#4E9A06">&apos;__rootModule__&apos;</font>,
    <font color="#4E9A06">&apos;__rootModule__?commonjs-entry&apos;</font>,
    <font color="#4E9A06">&apos;/home/linus/test/lively.next/lively.morphic/index.js&apos;</font>,
    <font color="#4E9A06">&apos;/home/linus/test/lively.next/lively.graphics/index.js&apos;</font>,
    <font color="#4E9A06">&apos;/home/linus/test/lively.next/lively.freezer/src/landing-page.cp.js&apos;</font>,
    <font color="#4E9A06">&apos;/home/linus/test/lively.next/lively.classes/runtime.js&apos;</font>,
    <font color="#4E9A06">&apos;/home/linus/test/lively.next/lively.morphic/config.js&apos;</font>,
    <font color="#4E9A06">&apos;/home/linus/test/lively.next/lively.morphic/morph.js&apos;</font>,
    <font color="#4E9A06">&apos;/home/linus/test/lively.next/lively.morphic/world.js&apos;</font>,
    <font color="#4E9A06">&apos;/home/linus/test/lively.next/lively.morphic/text/morph.js&apos;</font>,
    <font color="#4E9A06">&apos;/home/linus/test/lively.next/lively.morphic/text/label.js&apos;</font>,
    <font color="#4E9A06">&apos;/home/linus/test/lively.next/lively.morphic/text/anchors.js&apos;</font>,
    <font color="#4E9A06">&apos;/home/linus/test/lively.next/lively.morphic/text/range.js&apos;</font>,
    <font color="#4E9A06">&apos;/home/linus/test/lively.next/lively.morphic/html-morph.js&apos;</font>,
    <font color="#4E9A06">&apos;/home/linus/test/lively.next/lively.morphic/env.js&apos;</font>,
    <font color="#4E9A06">&apos;/home/linus/test/lively.next/lively.morphic/layout.js&apos;</font>,
    <font color="#4E9A06">&apos;/home/linus/test/lively.next/lively.morphic/components/core.js&apos;</font>,
    <font color="#4E9A06">&apos;/home/linus/test/lively.next/lively.morphic/style-sheets.js&apos;</font>,
    <font color="#4E9A06">&apos;/home/linus/test/lively.next/lively.morphic/rendering/morphic-default.js&apos;</font>,
    <font color="#4E9A06">&apos;/home/linus/test/lively.next/lively.morphic/rendering/dom-helper.js&apos;</font>,
    <font color="#4E9A06">&apos;/home/linus/test/lively.next/lively.morphic/rendering/animations.js&apos;</font>,
    <font color="#4E9A06">&apos;/home/linus/test/lively.next/lively.morphic/text/icons.js&apos;</font>,
    <font color="#4E9A06">&apos;/home/linus/test/lively.next/lively.morphic/serialization.js&apos;</font>,
    <font color="#4E9A06">&apos;/home/linus/test/lively.next/lively.morphic/morphicdb/index.js&apos;</font>,
    <font color="#4E9A06">&apos;/home/linus/test/lively.next/lively.morphic/text/input-line.js&apos;</font>,
    <font color="#4E9A06">&apos;/home/linus/test/lively.next/lively.morphic/helpers.js&apos;</font>,
    <font color="#4E9A06">&apos;/home/linus/test/lively.next/lively.graphics/color.js&apos;</font>,
    <font color="#4E9A06">&apos;/home/linus/test/lively.next/lively.graphics/geometry-2d.js&apos;</font>,
    <font color="#4E9A06">&apos;/home/linus/test/lively.next/lively.lang/index.js&apos;</font>,
    <font color="#4E9A06">&apos;https://jspm.dev/three&apos;</font>,
    <font color="#4E9A06">&apos;/home/linus/test/lively.next/lively.components/canvas.js&apos;</font>,
    <font color="#4E9A06">&apos;/home/linus/test/lively.next/lively.bindings/index.js&apos;</font>,
    <font color="#4E9A06">&apos;/home/linus/test/lively.next/lively.ide/studio/top-bar.cp.js&apos;</font>,
    <font color="#4E9A06">&apos;/home/linus/test/lively.next/lively.ide/studio/world-browser.cp.js&apos;</font>,
    <font color="#4E9A06">&apos;\x00rollupPluginBabelHelpers.js&apos;</font>,
    <font color="#4E9A06">&apos;/home/linus/test/lively.next/lively.lang/string.js&apos;</font>,
    <font color="#4E9A06">&apos;/home/linus/test/lively.next/lively.ide/shell/shell-interface.js&apos;</font>,
    <font color="#4E9A06">&apos;/home/linus/test/lively.next/lively.serializer2/index.js&apos;</font>,
    <font color="#4E9A06">&apos;/home/linus/test/lively.next/lively.morphic/CommandHandler.js&apos;</font>,
    <font color="#4E9A06">&apos;/home/linus/test/lively.next/lively.morphic/events/KeyHandler.js&apos;</font>,
    <font color="#4E9A06">&apos;/home/linus/test/lively.next/lively.morphic/ticking.js&apos;</font>,
    <font color="#4E9A06">&apos;/home/linus/test/lively.next/lively.morphic/components/policy.js&apos;</font>,
    <font color="#4E9A06">&apos;/home/linus/test/lively.next/lively.user/morphic/user-ui.js&apos;</font>,
    <font color="#4E9A06">&apos;https://jspm.dev/bowser@1.4.1&apos;</font>,
    <font color="#4E9A06">&apos;/home/linus/test/lively.next/lively.user/index.js&apos;</font>,
    <font color="#4E9A06">&apos;/home/linus/test/lively.next/lively.resources/index.js&apos;</font>,
    <font color="#4E9A06">&apos;/home/linus/test/lively.next/lively.morphic/tooltip-viewer.js&apos;</font>,
    <font color="#4E9A06">&apos;/home/linus/test/lively.next/lively.morphic/world-loading.js&apos;</font>,
    <font color="#4E9A06">&apos;/home/linus/test/lively.next/lively.morphic/text/position.js&apos;</font>,
    <font color="#4E9A06">&apos;/home/linus/test/lively.next/lively.ide/text/map.js&apos;</font>,
    <font color="#4E9A06">&apos;/home/linus/test/lively.next/lively.ide/diff/editor-plugin.js&apos;</font>,
    <font color="#4E9A06">&apos;/home/linus/test/lively.next/lively.morphic/text/selection.js&apos;</font>,
    <font color="#4E9A06">&apos;/home/linus/test/lively.next/lively.morphic/text/document.js&apos;</font>,
    <font color="#4E9A06">&apos;/home/linus/test/lively.next/lively.morphic/undo.js&apos;</font>,
    <font color="#4E9A06">&apos;/home/linus/test/lively.next/lively.morphic/text/layout.js&apos;</font>,
    <font color="#4E9A06">&apos;/home/linus/test/lively.next/lively.morphic/text/commands.js&apos;</font>,
    <font color="#4E9A06">&apos;/home/linus/test/lively.next/lively.morphic/text/attributes.js&apos;</font>,
    <font color="#4E9A06">&apos;/home/linus/test/lively.next/lively.morphic/rendering/property-dom-mapping.js&apos;</font>,
    <font color="#4E9A06">&apos;https://jspm.dev/css@3.0.0&apos;</font>,
    <font color="#4E9A06">&apos;/home/linus/test/lively.next/lively.notifications/index.js&apos;</font>,
    <font color="#4E9A06">&apos;/home/linus/test/lively.next/lively.lang/promise.js&apos;</font>,
    <font color="#4E9A06">&apos;/home/linus/test/lively.next/lively.morphic/rendering/renderer.js&apos;</font>,
    <font color="#4E9A06">&apos;/home/linus/test/lively.next/lively.morphic/rendering/font-metric.js&apos;</font>,
    <font color="#4E9A06">&apos;/home/linus/test/lively.next/lively.morphic/changes.js&apos;</font>,
    <font color="#4E9A06">&apos;/home/linus/test/lively.next/lively.morphic/events/EventDispatcher.js&apos;</font>,
    <font color="#4E9A06">&apos;https://jspm.dev/flubber&apos;</font>,
    <font color="#4E9A06">&apos;https://jspm.dev/bezier-easing&apos;</font>,
    <font color="#4E9A06">&apos;https://jspm.dev/web-animations-js&apos;</font>,
    <font color [...]

2023-02-06 21:38 UTC, linusha reviewed
@kholbekj thanks for this! I will merge this tomorrow. 

I am curious - did you run `make hooks` inside of your lively repo after cloning?
We have a (more or less good specified) convention for commit messages, yours should look more like `🛠️: add check for node 19`. No need to worry, I'll fix it up, but the pre commit hook should have catched that. Therefore, just asking to fix the hook if its faulty.

2023-02-06 21:46 UTC, kholbekj commented
I did not! Will fix going forward!

2023-02-07 10:20 UTC, linusha approved these changes

2023-02-07 10:29 UTC, linusha requested changes
Heh, I was too hasty there. I think `$node_version` needs to be `$NODE_VERSION`, as it was before. The boot check fails as it is because it thinks the node version to be too low.

Please just amend and force push the changes. I'd appreciate if you'd change the commit message as well, while we are at it. :slightly_smiling_face:

2023-02-07 11:26 UTC, kholbekj commented
Fixed node verison, curisouly even with make hooks having run, it dind't complain. Maybe because of the --amend?

2023-02-07 11:54 UTC, linusha approved these changes

2023-02-07 11:54 UTC, merged